### ISSUE TITLE
Add Violin

### ISSUE THREAD

**Issue by frainz-de** [thetwom/Tuner#16]
Could you maybe add the violin to the predefined instruments? Its strings are tuned to G, D, A and E. A is 440 Hz

**Comment by thetwom** [comment]
Thanks for asking. I will see, when I find time, and upload a test version, so you can check that it works correctly.

**Comment by thetwom** [comment]
Here is the test version [v2.1.0-beta1](https://github.com/thetwom/Tuner/releases/tag/v2.1.0-beta1). Would be great if you can give it a try.

**Comment by frainz-de** [comment]
Yes, it works. Thank you :)

**Comment by thetwom** [comment]
Thanks, tagged it as release now, so it will appear in fdroid and google play during the next days ...
