### ISSUE TITLE
Feature request: custom tunings

### ISSUE THREAD

**Issue by Ethanol6** [thetwom/Tuner#17]
Would it be at all possible to have a feature to add custom tunings? I don't know how hard this would be to implement but it would be fantastic.

**Comment by thetwom** [comment]
Thanks for your interest. This is a feature, which I had in mind for quite some time, but didn't take the time to implement it. 

What makes the integration a bit difficult, is to find a intuitive way to set the different tones. Also how to integrate it in the instruments list, what to do with the preset instruments, ... lots of things to think of :-). So it might take some time, until I get there ...

**Comment by Ethanol6** [comment]
To me it would be pretty intuitive to just pick notes from a chromatic scale. Displayed like piano keys vertically, so you could get 1.5 to 2 octaves on screen and have some display across the top edge (so your thumb doesn't cover it up) that shows 1st note, 2nd note, 3rd note etc. I'm no UX genius though.

Or a radial menu, musicians understand the circle of fifths so radial menus are pretty intuitive. Have the center of the circle display which octave based around C, so C1, C2, C3 etc. and then the outer slices would be the notes A through G. Have a toggle for sharp or flat otherwise you'd never fit all the notes around the circle.

I think custom tunings should have their own list so that users don't have to sort through an extensive list of custom tunings just to find the preset standard tunings.

Easier said than done though!

**Comment by thetwom** [comment]
thanks for the feedback. I will try around the next time a bit, but I fear it will take weeks, even months to get something final there due to my currently very limited time ...

**Comment by Ethanol6** [comment]
I know how FOSS works, take your time! Thanks for the fantastic app!

**Comment by thetwom** [comment]
I created a test version which allows using custom tunings. Maybe you are willing to test? [v3.0.0-beta1](https://github.com/thetwom/Tuner/releases/tag/v3.0.0-beta1)

**Comment by Ethanol6** [comment]
Nice! This works pretty well. I presume a few features are pending still? Deleting a custom tuning?

Here's one bug, when the screen locks, unlocking it returns to the instrument list "Edit Instrument" is displayed at the top but clicking the + no longer brings up the new tuning screen.

[Edit Screen](https://github.com/Ethanol6/Images/raw/main/EditInstrument.png)
[Edit Screen after lock/unlock](
https://github.com/Ethanol6/Images/raw/main/EditInstrument-PostScreenLock.png)

**Comment by thetwom** [comment]
Thanks for testing and also reporting the bug. Will see that I fix this soon. 
Mostly the implementation should be feature complete, so let me know if you are missing features.
Deleting tunings already works by swiping to the left, but maybe this is not intuitive? You can also reorder by long press a custom tuning and dragging to another place.
In your version also the numbers in the instruments overview are cut at the top, which will also be fixed ...

**Comment by Ethanol6** [comment]
I always forget about swiping right. Thanks.
I didn't see a way of editing a tuning after I've made it. Is this possible?

Being able to copy an instrument and then edit the copy would be convenient for alternate tunings which share notes with other tunings.

**Comment by thetwom** [comment]
Yes, editing a tuning is currently not possible. For a first usable version I assumed that this is not that important, but for future versions I am planning to address this. Copy-edit would also be nice, I agree, but as always one has to find good ways to allow this without cluttering the UI.

**Comment by Ethanol6** [comment]
> for future versions I am planning to address this.
That's perfect. Thanks so much for doing this.

**Comment by thetwom** [comment]
Here an update with fixes and allowing to edit/copy tunings: [v3.0.0-beta2](https://github.com/thetwom/Tuner/releases/tag/v3.0.0-beta2)
I you are able to test, please let me know, if the UI Design is understandable.

**Comment by Ethanol6** [comment]
The icons make sense. Long pressing the pencil to get to the copy option on custom instruments was a bit of a guess. Not sure what you can do there.

One issue...
https://github.com/Ethanol6/Images/raw/main/CopyInstrumentIcon.png
The "add instrument" + covers up the last instruments copy icon.

**Comment by thetwom** [comment]
Yes, it's a bit difficult to find a good way, but for now I think "long click" is a good compromise. "Copy-and-edit" is not a very necessary feature, so if people don't find it, I guess it's still quite usable :-). 

You are right, it's annoying that the last instrument copy icon is covered. In the next version, I will allow to scroll a bit further ...

**Comment by Ethanol6** [comment]
If this were on F-Droid I would just expect to see a note about the new features and how to use them in the release notes. I think this is very well done. Thanks so much for doing this.

**Comment by thetwom** [comment]
Not sure if many people read release notes :-). Lets accept for now, that some features are harder to find :-). 

Will do a few more (minor) improvements during the next days, so it will take some more time until I publish the official release.

**Comment by thetwom** [comment]
I released the version now with a few further improvements [v3.0.0](https://github.com/thetwom/Tuner/releases/tag/v3.0.0). Will appear on fdroid and play store soon.
