### ISSUE TITLE
Wrong octave

### ISSUE THREAD

**Issue by mirabilos** [thetwom/Tuner#2]
The octaves are off-by-one; A₄ is the 440 Hz one.

**Comment by thetwom** [comment]
Thanks for the hint! A4 is correct at 440 Hz,  but the subscript isn't raised at the next higher C but when reaching the next higher A. This is obviously wrong. Will fix this!

**Comment by thetwom** [comment]
I pushed a fix now. Will tag a bugfix release shortly ... Thanks again for reporting.

**Comment by thetwom** [comment]
Fixed with release 1.2.3
