### ISSUE TITLE
monochrome android 13 icon

### ISSUE THREAD

**Issue by andsofine** [thetwom/Tuner#21]

**Comment by andsofine** [comment]
oh, of course I don't want workarounds either. but if you suddenly make an icon before the release of android 13, I would be glad to see it in cayicons

**Comment by thetwom** [comment]
what is cayicons? 

dynamic icons mean just providing an additional monochrome icon ... this will be provided with the next tuner release, but it will only be used for android 13+

**Comment by andsofine** [comment]
this is an icon pack. fork of lawnicons

**Comment by thetwom** [comment]
I see, thanks for the info. Sorry to say that I won't take the time to do this. But feel free to do it yourself. I can provide the svg-file of the icon if needed.

**Comment by thetwom** [comment]
this is now merged in and official in version [v4.0.0](https://github.com/thetwom/Tuner/releases/tag/v4.0.0)
