### ISSUE TITLE
[Feature] Translations

### ISSUE THREAD

**Issue by Glandos** [thetwom/Tuner#24]
Thank you for this great application!

Do you have plans for translations?

**Comment by thetwom** [comment]
This depends on the input of translators. If you would like to contribute a new language, I am happy to support you with providing it.

**Comment by Glandos** [comment]
I would like to translate it to French. The only thing to do is to create a `value_fr.xml` and translate from https://github.com/thetwom/Tuner/blob/master/app/src/main/res/values/strings.xml?

**Comment by thetwom** [comment]
yes, you copy the `strings.xml` and replace english values with the french values. The  file goes into a newly created `values-fr` folder. You could either checkout the repository and file a pull request with your changes, or you simply post the file here, and I will add it. 

Could you please directly take the `strings.xml` from the materialyou-branch? I am planning to merge this to master soon and with this, no words would be missing.

**Comment by Glandos** [comment]
Thanks. I'm in the process of translation.
I see that note name can be translated. Most French speakers use the [solfège](https://en.wikipedia.org/wiki/Solf%C3%A8ge), but I don't know if it makes sense to translate this here (A->la, B->si, etc.) Do you have an opinion on this?

**Comment by thetwom** [comment]
We would be less prone of display issues, if you would keep A, B. If we use longer names, it can happen, that margins and so do not fit so well anymore. On the other side it would be a good test how robust the API works ...

I can't speak for French people and what is the most natural way of notes in a tuner, but in the end I would say: If French people can work with both equally, we better stay with A, B, ... however, if you think that the majority understands la, si, ... better, we could give this a try. But we would have to test this before publishing :-).

**Comment by thetwom** [comment]
interesting to know, maybe we should give a do-re-mi-setting a try some other day
