### ISSUE TITLE
App logo looks quite... interesting

### ISSUE THREAD

**Issue by Emporea** [thetwom/Tuner#26]
Is there a reason for the app icon to look like an erect penis?

**Comment by thetwom** [comment]
Not sure, if this is a serious comment. If it is, please open a new issue and try to explain your concerns in a more constructive way ...

**Comment by Emporea** [comment]
hehe i am not alone anymore.

**Comment by thetwom** [comment]
@summersab thanks for sharing your view in a constructive way. I really did hope, that this was just an unprofessional comment, but obviously (and as @Emporea  is saying), there are more people who are seeing an unfortunate shape in the logo. It seems like I don't get around changing it.

**Comment by Glandos** [comment]
Well, I have to give my opinion, that I am able to see penis in a lot of uncommon places, but for this one, I missed it. The logo seemed totally neutral to me. Except that, now I'm *educated*, I see it, of course.

**Comment by summersab** [comment]
I'm no graphic designer, but I did a quick bitmap trace, cleaned up the lines, and came up with these (SVG and PNG attached). Feedback?

![Tuner_ic_launcher-playstore](https://user-images.githubusercontent.com/18727110/186964347-f8c038db-c773-45d8-ac26-4fac72e21c40.png)
![Tuner_ic_launcher-playstore](https://user-images.githubusercontent.com/18727110/186964350-6863bec8-15d1-4a0d-93cd-edd1a6e4c02d.svg)
![Tuner_ic_launcher-playstore-curved](https://user-images.githubusercontent.com/18727110/186965022-55734cc5-50c8-42da-8d01-70fa00a9fd10.png)
![Tuner_ic_launcher-playstore-curved](https://user-images.githubusercontent.com/18727110/186965026-1216e8db-a0a9-4f95-8e17-8294c1e168e9.svg)

**Comment by thetwom** [comment]
@Glandos Thanks for your opinion, the situation is similar for me, but I guess, if two or more people take their time to write an issue, it can be assumed that it affects quite an amount of people.
@summersab Thanks a lot for your suggestions. Especially since you appear to not be using the app. Interesting idea to cut the arrow in half and give the appearance of a eighth note.  I will also be trying around a bit, and would be happy hearing feedback.

**Comment by thetwom** [comment]
![logos](https://user-images.githubusercontent.com/29151788/187030217-51f40b91-f9bb-4906-b9af-609775d62862.png)
Any opinions?

**Comment by Glandos** [comment]
I like the current arrow angle. I also think that separating the arrow from the base note with a space is a good idea to avoid this idea.
So first and second only. But even if I like the filled aspect, maybe the second one (with the whole note) will help to avoid the confusion even better.

**Comment by summersab** [comment]
Having the icon at an angle AND with the arrow really doesn't help the visual... "association." In my opinion, these would be the best possible style changes (in order of best to worst):
- No angle and half of the arrow
- No angle but with the arrow
- Angle but with half of the arrow

Half note (unfilled) doesn't really make a difference, nor does separating the stem from the note - those parts are up to your preference, in my opinion. The arrow and angle are really the biggest issues.

Also, I like the lighter blue color. Again, just a preference.

**Comment by thetwom** [comment]
I agree with @Glandos that no angle does not look so good. 

I really thought that small changes like having a half note or a separated arrow would help, so thanks for the feedback. 

I also reconsidered half an arrow, but thinking about it again, I really don't see that it would help. 

What about something like this?
![logos](https://user-images.githubusercontent.com/29151788/187043638-99466c5a-e87f-4d24-bee3-862074a53154.png)

Regarding color, no idea how to decide on this :-) ...

**Comment by summersab** [comment]
I liked the second, but my girlfriend liked the first. Either way, we both agreed that these are MUCH better.

**Comment by Emporea** [comment]
Sorry again for my apparently non-constructive first issue. 
I also like both, especially the whole note.
Thanks.

**Comment by summersab** [comment]
You were just blunt, @Emporea - nothing wrong with that, but things aren't always understood well via text-based communication. At any rate, I probably wouldn't have chimed in if I didn't see an existing issue filed by another user, so it works out in the end.

**Comment by thetwom** [comment]
@Emporea I highly appreciate your apologies. Obviously, you were right first place. So thank you for opening the issue even though I did close it.
@summersab Thanks for picking up the issue, such that I did finally address it.
@Glandos Thanks for your view on this issue and also helping to find a way to resolving it.

I still have to decide which logo to take, but I plan to integrate it in the next release. Might take some days (or even a few weeks), but the old logo is around for so long now, so I guess there is not hurry.

**Comment by Emporea** [comment]
Just wanted to say. I appreciate the new Icon. :)

**Comment by thetwom** [comment]
Good to hear, thanks for your help!

**Comment by summersab** [comment]
Just saw the new icon and showed it to my girlfriend. She said, "MUCH better..." Glad this got "fixed!" :-)

**Comment by thetwom** [comment]
Also good to hear :-). Thanks to you and your girlfriend for your support.

**Comment by DiegoBarrosA** [comment]
just came to give my thanks for this fix, this is my favorite tuning app and this problem was in my mind since forever. keep up the great work 🤗

**Comment by thetwom** [comment]
The thanks belongs to the ones who reported it :-)
