### ISSUE TITLE
Add an ability to filter background noise

### ISSUE THREAD

**Issue by eternal-sorrow** [thetwom/Tuner#36]
If there is some background noise when I'm tuning my guitar (for example someone is talking in the distance), the app goes all over the place when I don't play anything. Then I play a note and it suddenly jumps to the note I played. Then it jumps somewhere else when the note I played fades out or when I damp it.

**Comment by thetwom** [comment]
I can understand that it is annoying, when the app detects any tones one is not interested in. But depending on the situation it is a difficult task:
- Real noise can be filtered, actually there is an option of the maximum allowed noise in the settings, where you could turn up the noise level, at which the app does not try to detect notes.
- What you are describing is more difficult. If there is a voice in the background, the app can detect the pitch of this voice, which strictly speaking is no noise, but a valid signal. So, the app would have to evaluate the loudness of the signal. But suppressing quiet signals could also mean, that you cannot detect quiet instruments :-). 

That said, I don't say it is impossible to improve the current behavior. Currently, there is an update pending to improve the note detection, which is quite a big change. Maybe I find time afterwards to think about improvements of handling unimportant signals. 

In the meantime you can of course just select your target note, to lock the app to this note. Additionally you can drag the note-history manually to your preferred position ... then it at least won't jump. But I understand, that this is not really convenient.

**Comment by thetwom** [comment]
Closing this due to the similarity of #72.
