### ISSUE TITLE
Feature request: option to display sharp/flat names side by side

### ISSUE THREAD

**Issue by TallKite** [thetwom/Tuner#45]
Hi, inventor of ups/downs notation and the Kite guitar here. First of all, thank you for this wonderful app! The GUI is awesome! Seeing the tuning history in graph form is so nice!

An option to display the sharp name and the flat name side by side would be great. But in the lower half of the screen, this would make the tuning history window narrower. So perhaps the names would be one above the other? Or perhaps both names show up only in the top half of the screen?

Background: As a long-time microtonalist, I'm fine with the current state of the app. But we in the Kite guitar community do a lot of promoting 41edo to microtonal newbies. They have to go from 12edo straight to 41 without first using smaller edos like 17 or 22. Learning all the enharmonic equivalences can be overwhelming. The tuner they use is a natural place for them to learn that. True, they could use the #/b button to switch back and forth, but it's much easier for them if the 2 names are listed side by side.

**Comment by thetwom** [comment]
Hi, thanks for leaving this comment here. It's an honour to me to meet you who invented this notation. 

First of all, your request and reasoning makes totally sense to me. On the other side, as you say, it takes space and also it makes the UI appear less clean. Again on the other side, I am not UI designer and it is hard for me to tell, how much the users can tolerate. 

Then of course, one could add an additional setting, which would give the user the choice. But then, it is quite a challenge to make the UI behave nicely for all combinations of settings. 

Originally, we introduced this #/b switch as a compromise to not showing both options.

So, in the end, I tend to not take the challenge of introducing the requested change. Although I perfectly understand that for microtonal newbies it could be a substantial benefit.

**Comment by TallKite** [comment]
OK, fair enough. True, the #/b switch does most of what I want. Thanks for taking the time to think about it.
