### ISSUE TITLE
i found an open source polyphonic tuner

### ISSUE THREAD

**Issue by RustoMCSpit** [thetwom/Tuner#52]
take a look if you want https://github.com/DamRsn/NeuralNote

how hard would it be to port it / take its features and put it into android

**Comment by thetwom** [comment]
About which features are you talking here? After a quick glance, this does not look like a tuner.

**Comment by RustoMCSpit** [comment]
> About which features are you talking here? After a quick glance, this does not look like a tuner.

sorry not a tuner but it finds notes. i thought youd find it interesting and maybe could see if there were features you wanted there. thanks for all you d

**Comment by thetwom** [comment]
Closing this now, since it is neither a real "issue"  nor a feature request.
