### ISSUE TITLE
irrelevent request

### ISSUE THREAD

**Issue by RustoMCSpit** [thetwom/Tuner#53]
was wondering if you knew how / wanted to set up this midi file github page resource
https://github.com/Fannon/midi-chords-and-scales-pack/issues/2

heres a list of free midi resources, i want there to be a singular github for everyone to access them

**Comment by thetwom** [comment]
sorry for the late reply. Do not really get your question here. You want to start a github project, where all you do is to collect midi ressources? Just create a new project and put all your text into the readme of the main page.

**Comment by thetwom** [comment]
Closing this now since this is a bit offtopic :-)
