### ISSUE TITLE
Tuner & Metronome

### ISSUE THREAD

**Issue by Maha-Rajan** [thetwom/Tuner#54]
Currently both your Tuner and Metronome apps are by far the best implementation of these tools in my opinion, and I love using them on a daily basis. the only request I have is if there was an app the has both the functionality in one place...

**Comment by vocna** [comment]
I agree @thetwom's Tuner and Metronome are amazing, but merging them into one program or monolithic programs in general are always a bad idea. Tuner and metronome are completely separate task.
Although, I totally understand you idea and point (musician needs these both every day), but still I opposite it.

**Comment by thetwom** [comment]
Closing this, since this is basically the same as issue #73
