### ISSUE TITLE
Setting titles are cut off

### ISSUE THREAD

**Issue by Glitchy-Tozier** [thetwom/Tuner#6]
Not sure what to do here but it's not great having to turn your phone sideways to even understand the settings.

![Screenshot_20210627-131227_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123542964-b2ab7700-d74c-11eb-95aa-a115038e5bea.jpg)

**Comment by thetwom** [comment]
You are right. this indeed is annoying, but I didn't find shorter names. Maybe I can give it another thought. On the other hand, I would guess that the settings are not used very frequently. So maybe it's ok to request landscape ... 
But in total, I agree that this is not ideal.

**Comment by Glitchy-Tozier** [comment]
Yeah, it's difficult... The only thing I can think of rn is "Bessere" instead of "Verbessere"...

Are linebreaks an option?

Btw, I have the same issue further up:
![Screenshot_20210627-145728_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123545431-3c147680-d758-11eb-8a48-8f05bd7b6309.jpg)

**Comment by thetwom** [comment]
I am now allowing line breaks for long title. See [v1.2.4](https://github.com/thetwom/Tuner/releases/tag/v1.2.4-beta1).

**Comment by Glitchy-Tozier** [comment]
Great!

I try to avoid non-store app-sources so I won't test it now, but i'll happily try it out once it's released.  :)

**Comment by thetwom** [comment]
I issued now a new release. So please let me know what you think ...

**Comment by Glitchy-Tozier** [comment]
Looks great. Closing the issue♪
