### ISSUE TITLE
Helmholtz notation

### ISSUE THREAD

**Issue by vocna** [thetwom/Tuner#60]
Add [Helmholtz notation](https://en.m.wikipedia.org/wiki/Helmholtz_pitch_notation). It's important at least here in Nordic where Helmholtz is more common than [International notation](https://en.m.wikipedia.org/wiki/Scientific_pitch_notation) and it's confusing when  tuner speaks a different "language".

International notation:
... C₀ ... C₁ ... C₂ ... C₃ ... C₄ ... C₅ ...
Helmholtz notation:
... C₂ ... C₁ ... C ... c ... c¹ ... c² ...

I think this is also pretty trivial to implement.

**Comment by vocna** [comment]
Sorry for ping😅, but can you do this @thetwom? I don't want to pressure you, but this is so important feature to me since using the same notation in tuner would be clearer for my young students. This is my number one wish for this tuner; number two is #55.

**Comment by thetwom** [comment]
I have to see how easy this is, and how to do it best. It might be trivial to implement, but such wishes sometimes end up not in only implementing one additional notation, but we might need combinations (e.g. that it works together with all current notations).

**Comment by thetwom** [comment]
You can test Helmholtz notation now: [v6.5.0-rc1](https://github.com/thetwom/Tuner/releases/tag/v6.5.0-rc1) 

Would be nice to hear, if it works as expected ...

**Comment by thetwom** [comment]
Done
