### ISSUE TITLE
Material 3

### ISSUE THREAD

**Issue by vocna** [thetwom/Tuner#62]
Update the rest of the UI to Material 3 design.

E.g. these are still Material 2:
![Screenshot_20231006-151453__01__01](https://github.com/thetwom/Tuner/assets/147154374/d744718d-ee55-4e9c-8098-87da191e4a20)
Here Material 3:
![Screenshot_20231006-152011__01](https://github.com/thetwom/Tuner/assets/147154374/1a22e00f-2396-4dcc-b16e-bb6a3e8a8339)
![Screenshot_20231006-152036__01](https://github.com/thetwom/Tuner/assets/147154374/3dd64803-3d6a-417c-b797-dad1b12f77d5)

**Comment by thetwom** [comment]
I guess it is time to do the switch :-). This is not so well supported by the standard libs, which are used, but in the meantime the situation seems a bit better ...

**Comment by thetwom** [comment]
This is now done.
