### ISSUE TITLE
Tone feature

### ISSUE THREAD

**Issue by vocna** [thetwom/Tuner#64]
Please add tone/tuning fork feature. I think, the UI for that could be, when user click tone, then that tone play.

1|2
:-:|:-:
![Screenshot_20231006-153850__01__01__01](https://github.com/thetwom/Tuner/assets/147154374/05f84f51-25e5-4d41-a2aa-d8a44b41f9cf)|![Screenshot_20231006-153844__01__01](https://github.com/thetwom/Tuner/assets/147154374/e3f6e075-5d6f-427c-8d7a-fd3353598a83)

**Comment by thetwom** [comment]
Yes, lets close this issue and discuss this in #55. Your API suggestion seems obvious, but is in conflict that by selecting a note, you manually choose your target note. For the upper left diagram of your picture, selecting notes works already. I didn't manage yet to do this for the other diagrams, but in theory, this  would work ...
