### ISSUE TITLE
Add line break in about

### ISSUE THREAD

**Issue by Glitchy-Tozier** [thetwom/Tuner#7]
(Between version and licence)
![Screenshot_20210627-133743_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123543020-f7cfa900-d74c-11eb-8c7b-7bf978b1ea3f.jpg)

**Comment by Glitchy-Tozier** [comment]
Oh, and I assume you also want a linebreak after "Tuner app".

**Comment by thetwom** [comment]
You are right! Will change this shortly ... Thanks!

**Comment by thetwom** [comment]
Fixed in [v1.2.4](https://github.com/thetwom/Tuner/releases/tag/v1.2.4-beta1)
Tanks again for letting me know!

**Comment by Glitchy-Tozier** [comment]
Nice, good job!
