### ISSUE TITLE
Extended 1/4 meantone

### ISSUE THREAD

**Issue by HubbyG** [thetwom/Tuner#70]
Would it be easy enough to knock up an extended 1/4 meantone temperament which has all the usuals plus Eb Bb F# G# C#  but also caters for instruments with a few split sharps i.e. extra D# A# & Ab and so 15 pitches per octave?

(I see the similar 31 edo has all 31 pitches defined, so looks doable)

**Comment by thetwom** [comment]
Defining scales is kept pretty generic. So it should not be very difficult (as a long as there is nothing exotic, which is not covered yet by the implementation). The more difficult question is about which scales to deliver with the app. At the moment, there is no option to add custom scales, so only options are:
- Add new scale to the official version of the app (but this should be a scale of general use, no very rare cases)
- Fork the app and add it manually to your own needs.

**Comment by HubbyG** [comment]
Hello,
Thank you for your reply. It is wonderful to see rarely used temperaments like 31edo (and others) already on the tuning app.

I understand that the app may only become usable to my requirement if and when there is a user definable option.  Alas, I don't have the skills to fork the app.  I suppose I could try to employ someone as you imply the work is straightforward, but, have little idea how to approach this and at what cost(?)



6 Nov 2023, 18:14 by ***@***.***:

**Comment by thetwom** [comment]
Yes, the difficult question at the moment is to decide, what is rare, and what not.

We have to separate two things here:
- Adding a new scale to the app should be doable quite quickly, since the structure prepared for that.
- Having an user definable option. This is very challenging, because you need user interaction. Especially for non-12-tone-scales it is hard since the user must be able to provide note names. This is not very quickly done. 

Maybe your requested scales are still worth trying to add? Not sure if this is just personal for you or if it is also used by others? Is there literature about it? Maybe you could describe, how it is constructed. Just having cent values for each note? Or is it based on ratios?

**Comment by HubbyG** [comment]
Extended 1/4 comma meantone (meantone with three split sharps)
is described on this website <https://www.hpschd.nu/index.html?nav/nav-4.html&t/welcome.html&https://www.hpschd.nu/tech/tmp/faq.html>:

Scroll down to Temperament Index FAQ and choose Split Wolf Quarter comma page... 

It shows the additional 1/4SC fifths to facilitate the three extra pure major thirds (cf 1/4 meantone and 31 edo already on app)
🤞🏻



7 Nov 2023, 20:14 by ***@***.***:

**Comment by HubbyG** [comment]
Additional information here:
https://thegraphicalguidetotunings.blogspot.com/p/meantone-14-sc-splitwolf.html



7 Nov 2023, 22:07 by ***@***.***:

**Comment by thetwom** [comment]
Maybe you can try this: [v6.5.0-splitwolf](https://github.com/thetwom/Tuner/releases/tag/v6.5.0-splitwolf)
Most important to check would, if it is correctly implemented. E.g. if you select the temperament, you find the cent values there. These must be correct. For a quick check I list them here:
```
0.00,  // c   
76.05,  // c#  
193.16,  // d   
269.21,  // d#  
310.26,  // eb  
386.31,  // e   
503.42,  // f   
579.47,  // f#  
696.58,  // g   
772.63,  // g#  
813.69,  // ab  
889.74,  // a   
965.78,  // ais 
1006.84,  // bb  
1082.89,  // b   
1200.00,  // cs
```
Or let me know if you need additional info for being able to check.

**Comment by HubbyG** [comment]
Wow!  Many thanks :)

Those cent values you sent, correlate exactly with my calculations/expectations and checking against my keyboard, your tuner app (to my ear) seems to be correctly hearing the additional 3 pitches per octave.  

I usually use both A415 and A440 as reference pitches and I just did a precursory check with Tuner V6.5.0 on reference pitch A415 and all seems good.

One small point -  this shouldn't really be called "split-wolf 1/4 meantone" (easy to confuse given some of the reference material sent is calling it this - which is in fact yet another temperament for standard 12 notes / octave keyboards where the G# key is pitched 1/2 way between G# & Ab in 1/4 meantone terms)...
However, you have provided me with exactly the functionality I wanted, though to avoid confusion I would rename this in the Tuner app as either  "split-sharps 1/4 meantone" or "extended 1/4 meantone" as it is really useful for typical (albeit rare) period keyboards with either 13, 14 or 15 keys per octave (which have the usual 12 x 1/4 meantone notes + additional D#, Ab & A# respectively)

Your work will assist the tuning of any such instruments.  
Do you have a 'buy me a coffee" link so that I may thank you for this work?

Byron




8 Nov 2023, 20:46 by ***@***.***:

**Comment by thetwom** [comment]
Thanks for trying so quickly. Good to know, that the scale is correct. Thanks for the remark about the naming. I will adapt this accordingly. If you find other issues  (also small issues, similar to the naming, let me know). 

There is no "buy me a coffee" link. Still, thanks for willing to support this project.

**Comment by thetwom** [comment]
Ok, (hopefully) improved naming is now in the next release candidate [v6.5.0-rc2](https://github.com/thetwom/Tuner/releases/tag/v6.5.0-rc2). Will wait a few days, then make it official

**Comment by HubbyG** [comment]
Thank you so much again.

I'm very glad you chose 'Extended 1/4 comma meantone' for this temperament's title as I believe this would be the clearest and most succinct.

In your previous email, you asked me to mention any other small points I might notice, so two little ones both in the 'Temperament   Extended 1/4 comma meantone' pop up window when selecting this temperament:

1)  A case of semantics - in the brief further description, perhaps rather than 'perfect', instead use 'pure' and so might better read, 

  "Pure Major 3rds, 15 notes"

'Pure' as in 'Just' (i.e. no beats) would be clearer as opposed to 'Perfect' which can apply to intervals in many temperaments other than just 1/4 comma variants.
(e.g. perfect 5ths in 1/4 comma meantone are perfect but not pure, as they are 1/4sC narrower than pure.  But, perfect major 3rds in meantone however are pure as in the harmonic series sense of pure)

2)  Would be nice to see the message which can scroll underneath the cent values in the same window describing the sequence of 5ths - Not a circle per se, but a spiral, For example:
  "Spiral of fifths"
Ab --1/4 sC-> Eb --1/4 sC -> Bb --1/4 sC-> F --1/4 sC-> C --1/4 sC -> G --1/4sC-> D --1/4sC-> A --1/4sC-> E --1/4sC-> B --1/4sC-> F# --1/4sC-> C# --1/4sC-> G# --1/4sC-> A#

I must congratulate you further - this would be the only app known to me with Extended 1/4 Meantone available anywhere and I will tell all my music circle of this unique app whom I am sure will use it as a result.

So no 'by me a coffee' link! but do you have any other means by which we can encourage or support this fabulous project?

Byron




9 Nov 2023, 19:24 by ***@***.***:

**Comment by HubbyG** [comment]
...Adding to my small point (1) from just before:

'Pure Major 3rds' would also be appropriate for 1/4 (syntonic) Comma Meantone and
'Pure Minor 3rds' for 1/3 (syntonic) Comma Meantone  

Note: though not 'Pure' for their similarly named Pythagorian counterparts which Tuner doesn't currently offer anyway.




9 Nov 2023, 20:19 by ***@***.***:

**Comment by thetwom** [comment]
Thanks for naming the further issues. The explanations in respect of the wording make sense to me. Will change this for the official release. 

About showing the sequence of fifths. I also agree, that this would be nice to have. Just showing cent values is pretty abstract and makes it much harder to understand. It would also help to better know whether this is the tuning, which one would expect. Unfortunately, the current code structure makes this a bit difficult, so for now I will leave it without showing the sequence of fifths. 

>  but do you have any other means by which we can encourage or support this fabulous project?

For the scope of this project it is not necessary. I think this is bit different to other projects, where the developers make a living from it. I am glad I could help a little and it is interesting to understand at least a bit, that music has more dimensions than our standard 12-note scale.

**Comment by HubbyG** [comment]
😁👍🏻
You are truly very modest.  How wonderful to unite your coding skills with your understanding and appreciation of diverse musical instrument tunings... And then share freely 🙏🏻

I understand about there maybe coding issues in showing a cycle of fifths with more than 12 '5ths'... I can see the other various non-12 pitch systems to choose from also presently show cent values only.

It occurs Extended 1/4 meantone on your Tuner app will have more uses that at first was conceived for 'split sharp' keyboards with 13-15 keys per octave:

- still useful for conventional 12 keyed keyboards as can choose where a wolf 5th may lie (not just the diminished 6th usually positioned G#-Eb) without the need to change to another shifted arrangement of 1/4sC meantone temperament.

- useful for fretted instruments which may add some split frets (or tastini) to extend the usefulness of 1/4sC meantone beyond the limitations of the 'church modes' on their instruments, and enjoy those extra pure 3rds (and extra wolves😆 too).
- useful for ear training for instruments which are neither fixed, or semi-fixed pitched... I.e. free - voice, violins, trombones etc etc
...there will be no doubt more uses yet to be realised.
So much appreciation from this end. Will be great to see the release version in the coming days. (Qudos also for including Helmholtz notation too 👏🏻)

🙏🏻Byron




10 Nov 2023, 20:07 by ***@***.***:

**Comment by thetwom** [comment]
Indeed, interesting to see, that extended meantone might be quite helpful for more scenarios.

> your understanding and appreciation of diverse musical instrument tunings

Not really understanding ... I think I get some of theoretical ideas, but to be honest, practice is non-existent for everything beyond edo12 :D. Which is a bit of a pity, but time has its limits :-).

>  I can see the other various non-12 pitch systems to choose from also presently show cent values only.

All other non-12 scales are actually EDO scales, to my knowledge they are not based on cycles of fifths. Which is the reason, why it isn't shown. Actually, some of the 12-tone scales do also not show circle of fifths, since they are based on rational number ratio instead of circle of fifths (but then the ratios are shown).

> Qudos also for including Helmholtz notation too 

This request actually came from here #60 :-)

**Comment by HubbyG** [comment]
You are quite right in saying EDOs are based on rational number ratios AND also have a complete cycle of tempered 5ths ;) 
(see attached schematic)

Such a vast subject... One might say, 'so many temperaments, so little time'😆
Byron




10 Nov 2023, 22:39 by ***@***.***:

**Comment by HubbyG** [comment]
Is there an anticipated formal release imminent? 🙏🏻
Byron




10 Nov 2023, 23:17 by ***@***.***:

**Comment by thetwom** [comment]
Valid question :-). I took the opportunity and realeased [v6.5.0](https://github.com/thetwom/Tuner/releases/tag/v6.5.0). As for fdroid and google play this might take a few day to pick it up.

**Comment by thetwom** [comment]
What do you think? Should we close this issue or are there remaining requests?

**Comment by HubbyG** [comment]
This is all great, thank you again. 
I have been using and it is truly wonderful to have this extended temperament available for wider use.  I'll keep in touch if anything else occurs 🙏🏻
Byron




23 Nov 2023, 20:14 by ***@***.***:
