### ISSUE TITLE
Add unit to setting

### ISSUE THREAD

**Issue by Glitchy-Tozier** [thetwom/Tuner#8]
Not sure what that setting is but the 8000 should probably have a unit.
![Screenshot_20210627-150148_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123545560-e7bdc680-d758-11eb-876a-69916928b19a.jpg)

**Comment by Glitchy-Tozier** [comment]
Also a space after the colon would be nice.

**Comment by thetwom** [comment]
This indeed has no real unit, but I added now "samples" behind it, so that it is clearer what it is [see v1.2.4](https://github.com/thetwom/Tuner/releases/tag/v1.2.4-beta1). 
Colon space is also fixed now.
Thanks for the feedback.

**Comment by Glitchy-Tozier** [comment]
Great, looking forward to seeing the new settings "in action"  😄

**Comment by thetwom** [comment]
Is this issue fixed for you?

**Comment by Glitchy-Tozier** [comment]
Jup, closing thie issue ♪
