### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by ahangarha** [thetwom/Tuner#82]
Please include the LICENSE file so that the repo follows the common conventions of having a copy of the license in the repo.

**Comment by thetwom** [comment]
The file (COPYING) is in the app folder. But maybe I should better move it to the root folder, true.

**Comment by ahangarha** [comment]
That should work 👍🏾

**Comment by ahangarha** [comment]
It is done in 819ca9eb608

Thanks
