### ISSUE TITLE
FR: Parallagi (byzantine solfege)

### ISSUE THREAD

**Issue by anaskaejdar** [thetwom/Tuner#92]
Hi, I'd just like to request another alternate note naming scheme be added. This is the solfege-style naming in common use in byzantine music theory.

| Original | Latinized | Western equivalent |
| --- | --- | --- |
| Νη | Ni | Do/Ut |
| Πα | Pa | Re |
| Βου | Vou | Mi |
| Γα | Gha | Fa |
| Δι | Dhi | Sol |
| Κε | Ke | La |
| Ζω | Zo | Si/Ti

**Comment by thetwom** [comment]
Thanks for you request. Two small questions:
- I guess, the latinized names is, what you request. Depending on the translations, one can of course also use the original for certain languates.
- Do you have some references (links) which support the table?

**Comment by anaskaejdar** [comment]
If it's up to me and my preferences, I'd choose the version with the greek letters. I figured you'd prefer the latinized version, since the Carnatic and Hendustani scales are latinized.

Yeah, so here's a link: http://ebooks.edu.gr/ebooks/v/html/8547/2180/Mousiki_E-Dimotikou_html-empl/index14.html

And another good source which is in english is John Michael Boyer's book: “The Received Tradition” but I don't expect you to spend $80 just to get that table, so here's a relevant page:
![Screenshot_۲۰۲۴-۱۲-۱۴-۰۴-۱۳-۲۲-۱۶_2fb717c0403b9f26e585dd53ef609bab](https://github.com/user-attachments/assets/34579f2f-0a78-453a-8801-c1b9315a9ee4)

**Comment by thetwom** [comment]
I implemented it in the latest test version: [v7.0.0-rc4](https://github.com/thetwom/Tuner/releases/tag/v7.0.0-rc4). Please note that this version has many many more changed compared to v6... . So there might be some regressions (hopefully note).

**Comment by anaskaejdar** [comment]
Yeah, the original forms are _inescapable_ regardless of language. Even if an english composer wants to latinize the names, he/she can latinize it in the mode signature (vaguely like key signature) and in the ison (drone tone) markings, but he/she can't go changing them in the martyriae because its all too integrated there.

So even if it's music written for the romanian or spanish or english languages, with the latin alphabet, or it arabic or persian with their alphabets, the greek note names will always still show up untransliterated. See these examples:

<details><summary>A couple examples</summary>

![Screenshot_۲۰۲۴-۱۲-۱۴-۱۳-۰۴-۳۰-۲۲_2fb717c0403b9f26e585dd53ef609bab](https://github.com/user-attachments/assets/630186b1-1260-4655-804f-13ad584832eb)
![Screenshot_۲۰۲۴-۱۲-۱۴-۱۳-۰۸-۲۸-۵۰_2fb717c0403b9f26e585dd53ef609bab](https://github.com/user-attachments/assets/2e515a05-ebc2-4ded-ac8d-fdaec2c06d7c)

</details>

**Comment by thetwom** [comment]
So for now I used the original notation. Feel free to give it a try. Not sure how much I wait until I make an official release.

**Comment by Glandos** [comment]
>  (hopefully note).

I like this typo. A lot. :+1:

**Comment by anaskaejdar** [comment]
I think we can safely count this as done 100% — Reopen if you disagree. Thanks for all you do cap'n ❤️
